language: python

python:
  - "3.6"

before_install:
  - cd swe_app1

install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - black --check .
  - flake8 .
  - python manage.py test
  - coverage run --source "." manage.py test

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: us-east-1
  app: swe_app1
  env: swe-app1-env
  bucket_name: elasticbeanstalk-us-east-1-820971325727
  on:
    branch: main